### ISSUE TITLE
run crash

### ISSUE THREAD

**Issue by maxwell44** [Yalantis/PixPic#5]
ErrorMessage:    PFParameterAssert(clientKey.length, @"`clientKey` should not be nil.");

**Comment by serejahh** [comment]
hi @maxwell44. Thanks for your interest!

Yes, we didn't push our [keys to parse](https://github.com/Yalantis/PixPic/blob/b4b74c6f9cdd4482f5208d0dbd352cc8d12e7783/PixPic/Resources/Constants.swift#L14). You can create your app on Parse and add the keys
