### ISSUE TITLE
Run Crash

### ISSUE THREAD

**Issue by charsdavy** [Yalantis/PixPic#6]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '`clientKey` should not be nil.'

How to get `clientKey`?

**Comment by serejahh** [comment]
Hi @charsdavy! 

Your issue is a duplicate of #5. You should create an app on Parse and add your keys to [constants](https://github.com/Yalantis/PixPic/blob/b4b74c6f9cdd4482f5208d0dbd352cc8d12e7783/PixPic/Resources/Constants.swift#L14)

**Comment by charsdavy** [comment]
https://developers.facebook.com/docs/ios/getting-started?locale=zh_CN ，thanks
