### ISSUE TITLE
Xcode 8.1

### ISSUE THREAD

**Issue by ilyarmnzhdn** [Yalantis/PixPic#8]
I have got this bug, how can I fix it?
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by serejahh** [comment]
It's written on Swift 2.3 which is legacy. Once we will need to publish any updates, we'll the app to Swift 3
