### ISSUE TITLE
App Store Version Broken - No Backend Schema To Deploy App Against

### ISSUE THREAD

**Issue by ghost** [Yalantis/PixPic#9]
Unfortunately the app no longer works due to Parse being shut down in January this year.

**Comment by MchlBowyer** [comment]
Do you have a backup of the Parse storage or even just the schema? The app appears to build everything itself when run against a hosted Parse server, however the stickers part of the app is read only and there is no way to generate it without some more idea of what it should look like :( (P.S. Your app store published version of this app also doesn't work any more and crashes on launch)
